groups:
- name: scylla.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} has been down for more than 30 seconds.'
      summary: Instance {{ $labels.instance }} down
  - alert: InstanceDown
    expr: absent(scylla_transport_requests_served{job="scylla", shard="0"})
    for: 1m
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} instance is shutting down.'
      summary: Instance {{ $labels.instance }} down
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 25
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} has less than 25% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 10
    for: 30s
    labels:
      severity: "3"
    annotations:
      description: '{{ $labels.instance }} has less than 10% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 1
    for: 30s
    labels:
      severity: "4"
    annotations:
      description: '{{ $labels.instance }} has less than 1% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/"} / node_filesystem_size{mountpoint="/"}
      * 100 < 20
    for: 30s
    labels:
      severity: "3"
    annotations:
      description: '{{ $labels.instance }} has less than 20% free disk space on the root patition.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: NoCql
    expr: scylla_manager_healthcheck_cql_status == -1
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.host }} has denied cql connection for more than 30 seconds.'
      summary: Instance {{ $labels.host }} no cql connection